### ISSUE TITLE
선생님, 05.자바응용문제-2    5번 문제관련해서 질문드립니다.

### ISSUE THREAD

**Issue by PARKGAIN** [youngmoon525/java301_exam#1]
05. 자바 응용문제-2 5번 문제가  보기로 나온 소스코드에 오류가 있어서 수정하는 문제 맞죠???

**Comment by youngmoon525** [comment]
저 코드 그대로 자바 코드를 복붙하시고 역으로 오류가 없게끔 클래스나 메소드를 역으로 만들어내는 문제입니다.

**Comment by PARKGAIN** [comment]
> 저 코드 그대로 자바 코드를 복붙하시고 역으로 오류가 없게끔 클래스나 메소드를 역으로 만들어내는 문제입니다.

그렇군요 감사합니다 어렵네요 ㅎㅎ
